title: Tema personalizado Cayman
description: Your global VPN guide - Unlock Netflix, secure your privacy, and game without lag on public Wi-Fi
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#0f172a"
  gradient_left: "#065f46"   
  gradient_right: "#064e3b"  
logo_url: https://github.githubassets.com/images/icons/emoji/globe.png  # √çcono global
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://github.com/VPNuniverse/VPNuniverse.github.io
  zip_title: Download the VPNuniverse introduction
  zip_hide: false
  tar_hide: true
  github_hide: true
permalink: /:path/  # Soporte para subdirectorios
collections:
  es:
    output: true
  en:
    output: true